/**
 * Per-voyage Configuration History — an automatic audit log of every change
 * made to the Operations recap (Hire & Claims, Freight & Laytime, ETA &
 * Bunker, Cargo & Stowage, Voyage Details, everything), recording the date,
 * what changed and which user made the change.
 *
 * Entries are generated by diffing the recap before/after every save (see
 * `diffRecap`, called from `OperationsPage`'s single recap-persist effect —
 * this requires no per-field wiring). Backed by the tenant database (same
 * Settings key-value API as `opsRecap`): localStorage is the instant offline
 * cache, writes push through to the backend, and `hydrateConfigHistory` pulls
 * the server copy down.
 */
import { settingsApi } from '../api/settingsApi';

export interface ConfigHistoryEntry {
  id: string;
  /** ISO timestamp. */
  at: string;
  /** Who made the change. */
  by: string;
  /** Human-readable field/section name. */
  field: string;
  before: string;
  after: string;
}

const KEY = (voyageId: string) => `fv.opsConfigHistory.${voyageId}`;
const SETTING_KEY = (voyageId: string) => `opsConfigHistory.${voyageId}`;
const EVENT = 'fv-ops-config-history';
const MAX_ENTRIES = 500;
/** Above this many simultaneously-changed fields (bulk paste / CP fetch / voyage seed), log one
 *  consolidated entry instead of flooding the log with one row per field. */
const BULK_THRESHOLD = 12;

// Debounced write-through to the backend, same pattern as opsRecap.
const pushTimers = new Map<string, ReturnType<typeof setTimeout>>();
function debouncedPut(voyageId: string, list: ConfigHistoryEntry[]): void {
  const settingKey = SETTING_KEY(voyageId);
  const existing = pushTimers.get(settingKey);
  if (existing) clearTimeout(existing);
  pushTimers.set(settingKey, setTimeout(() => {
    pushTimers.delete(settingKey);
    void settingsApi.put(settingKey, list).catch(() => { /* offline — localStorage keeps it */ });
  }, 800));
}

export function loadConfigHistory(voyageId: string | undefined): ConfigHistoryEntry[] {
  if (!voyageId) return [];
  try {
    const raw = window.localStorage.getItem(KEY(voyageId));
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed as ConfigHistoryEntry[];
  } catch {
    /* ignore malformed */
  }
  return [];
}

function persist(voyageId: string, list: ConfigHistoryEntry[]): void {
  try {
    window.localStorage.setItem(KEY(voyageId), JSON.stringify(list));
  } catch {
    /* storage unavailable */
  }
  debouncedPut(voyageId, list);
  try {
    window.dispatchEvent(new CustomEvent(EVENT, { detail: { id: voyageId } }));
  } catch {
    /* ignore */
  }
}

/** Append new entries (newest first), capped at {@link MAX_ENTRIES}. */
export function appendConfigHistory(voyageId: string | undefined, entries: ConfigHistoryEntry[]): void {
  if (!voyageId || entries.length === 0) return;
  const next = [...entries, ...loadConfigHistory(voyageId)].slice(0, MAX_ENTRIES);
  persist(voyageId, next);
}

/** Pull the server copy of a voyage's config history into the local cache. */
export async function hydrateConfigHistory(voyageId: string | undefined): Promise<ConfigHistoryEntry[]> {
  if (!voyageId) return [];
  try {
    const res = await settingsApi.get(SETTING_KEY(voyageId));
    const parsed = JSON.parse(res.valueJson);
    if (Array.isArray(parsed)) {
      window.localStorage.setItem(KEY(voyageId), JSON.stringify(parsed));
      window.dispatchEvent(new CustomEvent(EVENT, { detail: { id: voyageId } }));
      return parsed as ConfigHistoryEntry[];
    }
  } catch {
    /* offline / not found — keep the local cache */
  }
  return loadConfigHistory(voyageId);
}

export function subscribeConfigHistory(voyageId: string | undefined, cb: () => void): () => void {
  if (!voyageId) return () => {};
  const onCustom = (e: Event) => {
    const detail = (e as CustomEvent).detail as { id?: string } | undefined;
    if (detail?.id === voyageId) cb();
  };
  window.addEventListener(EVENT, onCustom);
  return () => window.removeEventListener(EVENT, onCustom);
}

export function newConfigHistoryId(): string {
  return `ch-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
}

/** Friendly labels for the most-used recap fields; anything else falls back to a
 *  camelCase → Title Case conversion so every field still gets a readable name. */
const FIELD_LABELS: Record<string, string> = {
  vesselName: 'Vessel Name', vesselEmail: 'Vessel Email', vesselImo: 'IMO Number',
  voyageFixType: 'Voyage / Fix Type', owners: 'Owners', cpDate: 'CP Date',
  laycanStart: 'Laycan Start', laycanEnd: 'Laycan End', ownersBroker: "Owners' Broker",
  hirePerDay: 'Hire Per Day', charterers: 'Charterers', freightPerMt: 'Freight Rate',
  demDespatch: 'Demurrage / Despatch', despatchTerm: 'Despatch Term',
  deliveryPort: 'Delivery Port', deliveryTerm: 'Delivery Term', deliveryDateTime: 'Delivery Date & Time',
  redeliveryPort: 'Redelivery Port', redeliveryTerm: 'Redelivery Term', redeliveryDateTime: 'Redelivery Date & Time',
  wxClause: 'Weather Clause', ilohc: 'ILOHC', cve: 'CVE', adcom: 'Address Commission',
  brokerage: 'Brokerage', pniClub: 'P&I Club', ballastBonus: 'Ballast Bonus',
  cargoName: 'Cargo', cpQuantity: 'CP Quantity', holdCleaning: 'Hold Cleaning',
  finalQtyLoaded: 'Final Quantity Loaded', loadPort: 'Load Port', norAtLoadPort: 'NOR at Load Port',
  loadRate: 'Load Rate', pdaLoadPort: 'PDA (Load Port)', frtPaymentTerms: 'Freight Payment Terms',
  dischargePort: 'Discharge Port', norAtDPort: 'NOR at Discharge Port', dischRate: 'Discharge Rate',
  pdaDPort: 'PDA (Discharge Port)', foPrice: 'FO Price', doPrice: 'GO Price',
  cpSpeed: 'CP Speed', cpCons: 'CP Consumption',
  hirePayState: 'Hire Payment Status', charterHirePayState: "Charterers' Hire Payment Status",
  serviceProviders: 'Service Providers', bunkers: 'Bunkers', pnlNotes: 'Live P&L Notes',
  etaPlan: 'ETA & Bunker Itinerary', stowage: 'Cargo & Stowage Plan', freightLaytime: 'Freight & Laytime',
  hireDuplicates: 'Hire Payment Records', charterHireDuplicates: "Charterers' Hire Payment Records",
  hireScheduleSnapshot: 'Hire Schedule', charterHireScheduleSnapshot: "Charterers' Hire Schedule",
  cashflow: 'Cashflow', vesselReports: 'Vessel Reports', notes: 'Notes',
  eua: 'EUA / Emissions', additionalVoyageLegs: 'Additional Voyage Legs',
};

function labelFor(key: string): string {
  if (FIELD_LABELS[key]) return FIELD_LABELS[key];
  // camelCase -> Title Case fallback, e.g. "cpQuantityMin" -> "Cp Quantity Min".
  return key.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/^./, (c) => c.toUpperCase());
}

function summarizeValue(v: unknown): string {
  if (v == null || v === '') return '—';
  if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) return `${v.length} item(s)`;
  return 'Updated';
}

/** JSON.stringify with recursively-sorted object keys, so two logically-identical values that
 *  only differ in key insertion order never register as a "changed" field. */
function stableStringify(v: unknown): string {
  if (v == null || typeof v !== 'object') return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(stableStringify).join(',')}]`;
  const keys = Object.keys(v as Record<string, unknown>).sort();
  return `{${keys.map((k) => `${JSON.stringify(k)}:${stableStringify((v as Record<string, unknown>)[k])}`).join(',')}}`;
}

/** Shallow top-level diff between two recap snapshots — one entry per changed field, or a
 *  single consolidated entry when a large batch changed at once (paste / CP fetch / reseed). */
export function diffRecap(before: Record<string, unknown>, after: Record<string, unknown>, by: string): ConfigHistoryEntry[] {
  const keys = new Set([...Object.keys(before), ...Object.keys(after)]);
  const changed: string[] = [];
  for (const key of keys) {
    if (stableStringify(before[key]) !== stableStringify(after[key])) changed.push(key);
  }
  if (changed.length === 0) return [];
  const at = new Date().toISOString();
  if (changed.length > BULK_THRESHOLD) {
    return [{
      id: newConfigHistoryId(), at, by,
      field: `Bulk update (${changed.length} fields)`,
      before: '—',
      after: changed.map(labelFor).slice(0, 8).join(', ') + (changed.length > 8 ? ', …' : ''),
    }];
  }
  return changed.map((key) => ({
    id: newConfigHistoryId(),
    at,
    by,
    field: labelFor(key),
    before: summarizeValue(before[key]),
    after: summarizeValue(after[key]),
  }));
}
